version: '3'
services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tp3_ggg
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./app:/app
    depends_on:
      - postgres

volumes:
  postgres_data:

